# Generated by Django 5.0.3 on 2024-03-10 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='members',
        ),
        migrations.RemoveField(
            model_name='server',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='server',
            name='members',
        ),
        migrations.RemoveField(
            model_name='server',
            name='moderator',
        ),
        migrations.AddField(
            model_name='channel',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.server'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='refreshToken',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_owner', to='api.user'),
        ),
        migrations.CreateModel(
            name='DirectMessge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_updated', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='api.user')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='api.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MODERATOR', 'Moderator'), ('GUEST', 'Guest')], default='GUEST', max_length=20)),
                ('Channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_member', to='api.channel')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_member', to='api.server')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='api.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_updated', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_message', to='api.channel')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='api.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
