# Generated by Django 5.0.3 on 2024-03-16 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_member_server_server_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='members',
        ),
        migrations.AddField(
            model_name='member',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.server'),
            preserve_default=False,
        ),
    ]
