# Generated by Django 5.0.3 on 2024-03-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_server_members_member_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='server',
        ),
        migrations.AddField(
            model_name='server',
            name='members',
            field=models.ManyToManyField(related_name='server_member', to='api.member'),
        ),
    ]
